spring:
  application:
    name: XzjhMerchants
  datasource:
    url: jdbc:mysql://192.168.146.129:3306/passbook?useSSL=false&?characterEncoding=utf-8
    username: root
    password: Dmj921202
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
    multipart:
      location: D:\

  kafka:
    bootstrap-servers: 192.168.146.133:9092
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: jsp
server:
  port: 8008

logging:
  level: debug
  file: xzjh-merchants.log



